name: Auto Merge PRs from exercism-solutions-syncer

on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]'
    steps:
      - name: Auto-merge PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
