name: Auto-merge Dependabot PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR author
        run: |
          if [ "${{ github.actor }}" != "exercism-solutions-syncer[bot]" ]; then
            echo "❌ This workflow only runs for exercism-solutions-syncer[bot]."
            exit 1
          fi
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_METHOD: 'squash'
          MERGE_LABELS: ""
