name: Auto-Merge-PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Auto-Merge PRs
        uses: MinhOmega/auto-merge@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
